1. ### try/catch语句

   ```javascript
   try{
      //可能出错的代码
   }catch(err){
      //出错后的操作
   }finally{
   
   }
   ```

   - 任何可能出错的代码都应该放到try块中，而处理错误的代码则放在catch块中，如果try块中有代码发生错误，代码会立即退出执行，并跳到catch块中。catch块此时接收到一个对象，该对象包含发生错误的相关信息，即使不用，也要为它定义名称，基本所有浏览器都包含错误信息的message属性

     1. ##### finally子句

        - try/catch语句中可选的finally子句始终运行。如果try块中的代码运行完，则接着执行finally块中的代码。如果出错并执行catch块中的代码，则finally块中的代码仍执行。try或catch块无法阻止finally块执行，包括return语句
        - 只要代码中包含了finally子句，try或者catch中的return 语句就会被忽略

     2. #### 抛出错误

        - 与try/catch语句对应的一个机制是throw操作符，用于在任何时候抛出自定义错误。throw操作符必须有一个值，但值的类型不限

        - 使用throw操作符时，代码立即停止执行，除非try/catch语句捕获了抛出的值

        - 可以使用throw new +错误的构造函数来模拟浏览器错误

          1. 何时抛出错误

             抛出自定义错误是解释函数为什么失败的有效方式。在出现已知函数无法正确执行的情况时就应该抛出错误。

          2. 抛出错误与try/catch

     3.    #### error事件

           - 任何没有被try/catch语句处理的错误都会在window对象上触发error事件

     
### 2.调试技术

1. 将消息记录到控制台 ![image-20210331102201611](C:\Users\25760\AppData\Roaming\Typora\typora-user-images\image-20210331102201611.png)
2. 理解控制台运行时（REPL读取-求值-打印-循环）
3. 使用JavaScript调试器
   - debugger;的使用
4. 将信息在页面中打印
5. 补充控制台方法
6. 抛出错误

